#!/bin/bash

# make_machine_db architecture

usage() {
    echo make_machine_db architecture processor... >&2
    exit 2
}

[ $# -ge 2 ] || usage

set -e

arch="$1"
shift

db_name=`basename "$arch"`.db

rm -f "$db_name"

echo Creating "$db_name"

for f in machine.ddl "$arch/registers.sql" init.sql
do
    #echo reading "$f"
    sqlite3 -batch -init "$f" "$db_name" < /dev/null
done

python3.1 load_patterns.py "$db_name" "$arch/patterns"

for processor in "$@"
do
    #echo adding "$processor"
    sqlite3 -batch "$db_name" << !
        insert into pattern_by_processor (processor, pattern_id)
          select '$processor', id
            from pattern;
!
done
